# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Timer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Timer
pod 'Alamofire', '~> 4.5'
pod 'AlamofireObjectMapper', '~> 4.0'
pod 'SwifterSwift'
pod 'KeychainSwift', '~> 8.0'
pod 'Timberjack', :git => 'https://github.com/andysmart/Timberjack.git', :branch => 'master'

end
